services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: medbooker_api
    command: >
      bash -lc "
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        gunicorn backend.wsgi:application -b 0.0.0.0:8000 --workers 3
      "
    ports:
      - "8000:8000"
    env_file:
      - .env.api
    volumes:
      # keep your SQLite file on the host
      - ./db.sqlite3:/app/db.sqlite3
      # persist compiled static files (STATIC_ROOT=/app/staticfiles)
      - static_data:/app/staticfiles

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: medbooker_web
    ports:
      - "3000:3000"
    env_file:
      - .env.web
    depends_on:
      - api

volumes:
  static_data:
