// components/SidebarLink.tsx
"use client";

import Link from "next/link";
import type { Route } from "next"; // <- typed route union generated by Next
import { clsx } from "clsx";

export default function SidebarLink({
    href,
    children,
    className,
}: {
    href: Route;                 // <- strict, only valid app routes
    children: React.ReactNode;
    className?: string;
}) {
    return (
        <Link
            href={href}
            className={clsx(
                "block rounded-xl px-3 py-2 text-sm font-medium hover:bg-gray-100 transition",
                className
            )}
        >
            {children}
        </Link>
    );
}
